### ISSUE TITLE
Problem using turntable with xhtml

### ISSUE THREAD

**Issue by elEglon** [PolarNotion/turntable-slider#10] opened 2016-06-13 13:40 UTC
Dear reader/s,
Using html-docs turntable works as desired.
Trying to embed it into a xhtml-doc (needed for an eBook) it doesn't work any longer.
Any ideas are welcome.
Thank You and best wishes
Eglon

**Comment by Johnrae** [comment] 2016-06-13 18:25
Hey elEglon, 
Thanks for letting us know! I'm not sure how many eBook clients support javascript like this, but if you need to convert the plugin to create valid xhtml or xml tags, I have a quick fix for you. 

So I believe the issue is the plugin will append an image tag to your list, but its not self closing and not valid xhtml. If you grab the un-minified file and add a  "/"  on line 66 like so: 
This
`$(this).html('<img src="' + $(this).data("imgSrc") + '">');` 
Should be 
`$(this).html('<img src="' + $(this).data("imgSrc") + '"/>');`

Hope this helps!

**Comment by elEglon** [comment] 2016-06-14 07:36
Hi John,
Thank you for your info.
I talked to Morgan and we were able to solve the problem.
The fix you mention is working fine!
Best wishes
Eglon

**Closed as completed** 2016-06-14 10:42 UTC
